<?php
/*Template Name: Contact Us Template
 */

get_header();
?>

<div class="container">
     <div class="row">
         <div class="col-md-12">
<script src="https://cdn02.jotfor.ms/static/prototype.forms.js?3.3.35619" type="text/javascript"></script>
<script src="https://cdn03.jotfor.ms/static/jotform.forms.js?3.3.35619" type="text/javascript"></script>
<script type="text/javascript">	JotForm.newDefaultTheme = false;
	JotForm.extendsNewTheme = true;
	JotForm.newPaymentUIForNewCreatedForms = false;
		JotForm.newPaymentUI = true;
		JotForm.highlightInputs = false;

			JotForm.init(function(){
					/*INIT-START*/
				if (window.JotForm && JotForm.accessible) $('input_1').setAttribute('tabindex',0);
				if (window.JotForm && JotForm.accessible) $('input_3').setAttribute('tabindex',0);
				if (window.JotForm && JotForm.accessible) $('input_4').setAttribute('tabindex',0);
				      JotForm.setCustomHint( 'input_4', 'Type here...' );
					/*INIT-END*/
					});

		   JotForm.prepareCalculationsOnTheFly([null,{"description":"","name":"name1","qid":"1","subLabel":"","text":"Name","type":"control_textbox"},null,{"description":"","name":"email","qid":"3","subLabel":"","text":"Email","type":"control_textbox"},{"description":"","name":"message4","qid":"4","subLabel":"","text":"Message","type":"control_textarea"},{"name":"clickTo","qid":"5","text":"CONTACT US","type":"control_head"},{"name":"doubleclickTo","qid":"6","text":"Email:EMAIL US Address: Cape Town, South Africa","type":"control_text"},{"name":"submit","qid":"7","text":"SUBMIT","type":"control_button"},{"name":"sidebar","qid":"8","text":"sidebar - (not shown on actual form) - do not remove","type":"control_collapse"},{"name":"form","qid":"9","text":"form - (not shown on actual form) - do not remove","type":"control_collapse"}]);
		   setTimeout(function() {
			   JotForm.paymentExtrasOnTheFly([null,{"description":"","name":"name1","qid":"1","subLabel":"","text":"Name","type":"control_textbox"},null,{"description":"","name":"email","qid":"3","subLabel":"","text":"Email","type":"control_textbox"},{"description":"","name":"message4","qid":"4","subLabel":"","text":"Message","type":"control_textarea"},{"name":"clickTo","qid":"5","text":"CONTACT US","type":"control_head"},{"name":"doubleclickTo","qid":"6","text":"Email:EMAIL US Address: Cape Town, South Africa","type":"control_text"},{"name":"submit","qid":"7","text":"SUBMIT","type":"control_button"},{"name":"sidebar","qid":"8","text":"sidebar - (not shown on actual form) - do not remove","type":"control_collapse"},{"name":"form","qid":"9","text":"form - (not shown on actual form) - do not remove","type":"control_collapse"}]);}, 20); 
			   </script>
<style type="text/css">@media print{.form-section{display:inline!important}.form-pagebreak{display:none!important}.form-section-closed{height:auto!important}.page-section{position:initial!important}}</style>
<link id="custom-font" type="text/css" rel="stylesheet" href="https://cdn.jotfor.ms/opt/google-fonts/Cardo/fontface.css" />
<link type="text/css" rel="stylesheet" href="https://cdn01.jotfor.ms/themes/CSS/defaultV2.css?"/>
<link type="text/css" rel="stylesheet" href="https://cdn02.jotfor.ms/themes/CSS/548957a3700cc4ae108b4567.css?themeRevisionID=6140ab663e0d241aba34c1c1"/>
<link type="text/css" rel="stylesheet" href="https://cdn03.jotfor.ms/css/styles/payment/payment_styles.css?3.3.35619" />
<link type="text/css" rel="stylesheet" href="https://cdn01.jotfor.ms/css/styles/payment/payment_feature.css?3.3.35619" />
<form class="jotform-form" action="https://submit.jotform.com/submit/222444158224552/" method="post" name="form_222444158224552" id="222444158224552" accept-charset="utf-8" autocomplete="on">
  <input type="hidden" name="formID" value="222444158224552" />
  <input type="hidden" id="JWTContainer" value="" />
  <input type="hidden" id="cardinalOrderNumber" value="" />
  <div role="main" class="form-all">
    <style>
      .form-all:before { background: none;}
    </style>
    <ul class="form-section page-section">
      <li id="cid_5" class="form-input-wide" data-type="control_head">
        <div class="form-header-group  header-large">
          <div class="header-text httac htvam">
            <h1 id="header_5" class="form-header" data-component="header">
              CONTACT US
            </h1>
          </div>
        </div>
      </li>
      <ul class="form-section" id="section_9">
        <li id="cid_9" class="form-input-wide" data-type="control_collapse">
          <div class="form-collapse-table form-collapse-hidden" id="collapse_9" data-component="collapse">
            <span class="form-collapse-mid" id="collapse-text_9">
              form - (not shown on actual form) - do not remove
            </span>
            <span class="form-collapse-right form-collapse-right-show">
               
            </span>
          </div>
        </li>
        <li class="form-line" data-type="control_textbox" id="id_1">
          <label class="form-label form-label-left" id="label_1" for="input_1"> Name </label>
          <div id="cid_1" class="form-input" data-layout="half">
            <input type="text" id="input_1" name="q1_name1" data-type="input-textbox" class="form-textbox" data-defaultvalue="" style="width:310px" size="310" value="" placeholder=" " data-component="textbox" aria-labelledby="label_1" />
          </div>
        </li>
        <li class="form-line jf-required" data-type="control_textbox" id="id_3">
          <label class="form-label form-label-top form-label-auto" id="label_3" for="input_3">
            Email
            <span class="form-required">
              
	                   </span>
	                             </label>
	                                       <div id="cid_3" class="form-input-wide jf-required" data-layout="half">
	                                                   <input type="text" id="input_3" name="q3_email" data-type="input-textbox" class="form-textbox validate[required]" data-defaultvalue="" style="width:310px" size="310" value="" placeholder=" " data-component="textbox" aria-labelledby="label_3" required="" />
	                                                             </div>
	                                                                     </li>
	                                                                             <li class="form-line" data-type="control_textarea" id="id_4">
	                                                                                       <label class="form-label form-label-top form-label-auto" id="label_4" for="input_4"> Message </label>
	                                                                                                 <div id="cid_4" class="form-input-wide" data-layout="full">
	                                                                                                             <textarea id="input_4" class="form-textarea" name="q4_message4" style="width:648px;height:163px" data-component="textarea" aria-labelledby="label_4"></textarea>
	                                                                                                                       </div>
	                                                                                                                               </li>
	                                                                                                                                       <li class="form-line" data-type="control_button" id="id_7">
	                                                                                                                                                 <div id="cid_7" class="form-input-wide" data-layout="full">
	                                                                                                                                                             <div data-align="auto" class="form-buttons-wrapper form-buttons-auto   jsTest-button-wrapperField">
	                                                                                                                                                                          <button id="input_7" type="submit" class="form-submit-button form-submit-button-none submit-button jf-form-buttons jsTest-submitField" data-component="button" data-content="">
	                                                                                                                                                                                           SUBMIT
	                                                                                                                                                                                                         </button>
	                                                                                                                                                                                                                     </div>
	                                                                                                                                                                                                                               </div>
	                                                                                                                                                                                                                                       </li>
	                                                                                                                                                                                                                                             </ul>
	                                                                                                                                                                                                                                                   <ul class="form-section" id="section_8">
	                                                                                                                                                                                                                                                           <li id="cid_8" class="form-input-wide" data-type="control_collapse">
	                                                                                                                                                                                                                                                                     <div class="form-collapse-table form-collapse-hidden" id="collapse_8" data-component="collapse">
	                                                                                                                                                                                                                                                                                 <span class="form-collapse-mid" id="collapse-text_8">
	                                                                                                                                                                                                                                                                                               sidebar - (not shown on actual form) - do not remove
	                                                                                                                                                                                                                                                                                                           </span>
	                                                                                                                                                                                                                                                                                                                       <span class="form-collapse-right form-collapse-right-show">
	                                                                                                                                                                                                                                                                                                                                      
	                                                                                                                                                                                                                                                                                                                                                  </span>
	                                                                                                                                                                                                                                                                                                                                                            </div>
	                                                                                                                                                                                                                                                                                                                                                                    </li>
	                                                                                                                                                                                                                                                                                                                                                                            <li class="form-line" data-type="control_text" id="id_6">
	                                                                                                                                                                                                                                                                                                                                                                                      <div id="cid_6" class="form-input-wide" data-layout="full">
	                                                                                                                                                                                                                                                                                                                                                                                                  <div id="text_6" class="form-html" data-component="text">
	                                                                                                                                                                                                                                                                                                                                                                                                                <p>Email:<a href="mailto://admin@netbones.co.za" rel="nofollow">EMAIL US </a>Address: Cape Town, South Africa</p>
	                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
	                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
	                                                                                                                                                                                                                                                                                                                                                                                                                                              </li>
	                                                                                                                                                                                                                                                                                                                                                                                                                                                      <li style="display:none">
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                Should be Empty:
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <input type="text" name="website" value="" />
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </li>
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </ul>
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <script>
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              JotForm.showJotFormPowered = "new_footer";
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </script>
		                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <script>
		                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    JotForm.poweredByText = "Powered by Jotform";
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </script>
		                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <input type="hidden" class="simple_spc" id="simple_spc" name="simple_spc" value="222444158224552" />
		                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <script type="text/javascript">
		                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            var all_spc = document.querySelectorAll("form[id='222444158224552'] .si" + "mple" + "_spc");
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            for (var i = 0; i < all_spc.length; i++)
		                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {
			                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              all_spc[i].value = "222444158224552-222444158224552";
			                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
				                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </script>
				                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div class="formFooter-heightMask">
				                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
				                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </form>
				                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <script src="https://cdn.jotfor.ms//js/vendor/smoothscroll.min.js?v=3.3.35619"></script>
				                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <script src="https://cdn.jotfor.ms//js/errorNavigation.js?v=3.3.35619"></script>
				      
         </div>
     </div>
 </div>

<?php get_footer(); ?>

